// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkbGUfgR_qF1Mm2Q4jJTtyXbFQsEaNJPE',
    appId: '1:605309365926:web:3ecfc42ff3bf4489b7ce67',
    messagingSenderId: '605309365926',
    projectId: 'firedemo-1a385',
    authDomain: 'firedemo-1a385.firebaseapp.com',
    storageBucket: 'firedemo-1a385.appspot.com',
    measurementId: 'G-5VFQ6NWD6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGHv2c9JcDEWQLNPJnkqfgwofdkH3zK0',
    appId: '1:605309365926:android:7d6f7f525550ce3eb7ce67',
    messagingSenderId: '605309365926',
    projectId: 'firedemo-1a385',
    storageBucket: 'firedemo-1a385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0uPN3ZnkrxCl8nsVzEPI75XQExz_iJGY',
    appId: '1:605309365926:ios:98442aadcd2d68edb7ce67',
    messagingSenderId: '605309365926',
    projectId: 'firedemo-1a385',
    storageBucket: 'firedemo-1a385.appspot.com',
    iosClientId: '605309365926-ele3i823kaseat0h6o9t1hskg41vjc2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0uPN3ZnkrxCl8nsVzEPI75XQExz_iJGY',
    appId: '1:605309365926:ios:c0cedfde2bcabc3fb7ce67',
    messagingSenderId: '605309365926',
    projectId: 'firedemo-1a385',
    storageBucket: 'firedemo-1a385.appspot.com',
    iosClientId: '605309365926-dubdc21tj9pmn5ddb5sltc6mca004i2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo.RunnerTests',
  );
}
